version: '3'

services:
  db01:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: xlayer-api-sqlexpress01
    hostname: xlayer-api-sqlexpress01
    networks:
      - sxiws_net
    ports:
      - 1433:1433
    volumes:
      # ===== Windows Host =====
      - D:/code/XLayerAPI/sqlexpress/DB01:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=sXi_Pass
      - MSSQL_PID=Express

networks:
  sxiws_net:
    driver: bridge