version: '3.7'

services:
  db01:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: xlaye_api_sqlexpress01
    hostname: xlayer_api_sqlexpress01
    networks:
      - api_net
    ports:
      - 1433:1433
    volumes:
      # ===== Windows Host =====
      - D:/code/XLayerAPI/sqlexpress/DB01:/var/opt/mssql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=sXi_Pass
      - MSSQL_PID=Express

networks:
  api_net:
    external:
      name: xlayerapi