version: '3.7'

services:
  zoo1:
    image: confluentinc/cp-zookeeper:5.4.1
    #restart: unless-stopped
    container_name: xlayer_api_zoo01
    hostname: xlayer_api_zoo01
    networks: 
      - xlayerapi
    ports:
      - 2181:2181
    environment:
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_SERVER_ID=1
      - ZOOKEEPER_CLIENT_PORT=2181
      
  kafka1:
    image: confluentinc/cp-kafka:5.4.1
    depends_on:
      - zoo1
    #restart: unless-stopped
    container_name: xlayer_api_kafka01
    hostname: xlayer_api_kafka01
    networks: 
      - xlayerapi
    ports:
      - 9092:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=xlayer_api_zoo01:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://xlayer_api_kafka01:9092
      - KAFKA_DELETE_TOPIC_ENABLE=false
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - KAFKA_NUM_PARTITIONS=3
      - KAFKA_DEFAULT_REPLICATION_FACTOR=1

networks:
  xlayerapi:
    external: true